export default {
  // App
  QUIT_APPLICATION: 'QUIT_APPLICATION',

  // Users
  GET_ALL_USERS: 'GET_ALL_USERS',
  USERS_UPDATED: 'USERS_UPDATED',
  ROTATE_ACTIVE_USERS: 'ROTATE_ACTIVE_USERS',
  CLEAR_ACTIVE_USERS: 'CLEAR_ACTIVE_USERS',
  TOGGLE_USER_ACTIVE: 'TOGGLE_USER_ACTIVE',
  ADD_USER: 'ADD_USER',
  UPDATE_USER: 'UPDATE_USER',
  REMOVE_USER: 'REMOVE_USER',

  // Repos
  GET_ALL_REPOS: 'GET_ALL_REPOS',
  ADD_REPO: 'ADD_REPO',
  REMOVE_REPO: 'REMOVE_REPO'
}